consul:
  command: -server -bootstrap -advertise 192.168.99.100
  image: gliderlabs/consul-server:latest
  ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
registrator:
  command: -ip 192.168.99.100 consul://192.168.99.100:8500 
  image: gliderlabs/registrator:latest
  net: host
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
fabio:
  image: magiconair/fabio:latest
  ports:
    - "9999:9999"
    - "9998:9998"
  links:
    - "consul:consul"
  volumes:
    - "./fabio.properties:/etc/fabio/fabio.properties"
  environment:
  - SERVICE_9998_TAGS=urlprefix-/fabio